# Generated by Django 5.0.7 on 2024-07-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Regisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeValeurInactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=255)),
                ('valeur_faciale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ValeurInactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_feuillets', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_enreg', models.DateField()),
                ('type_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.typevaleurinactive')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('date_mouvement', models.DateField()),
                ('regisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regisseur.regisseur')),
                ('valeur_inactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.valeurinactive')),
            ],
        ),
    ]
