# Generated by Django 5.0.7 on 2024-07-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurinactive',
            name='montant_total',
            field=models.IntegerField(default=0),
        ),
    ]
