# Generated by Django 5.0.7 on 2024-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_alter_valeurinactive_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
