# Generated by Django 5.0.7 on 2024-07-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commune', '0001_initial'),
        ('Stock', '0003_mouvementstock_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiteDispo', models.PositiveIntegerField(default=0)),
                ('Montant', models.PositiveIntegerField(default=0)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
                ('type_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.typevaleurinactive')),
            ],
        ),
    ]
