# Generated by Django 5.0.7 on 2024-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0004_stockage'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeurinactive',
            name='nombre_valeur_feuillet',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='valeurinactive',
            name='nombre_feuillets',
            field=models.PositiveIntegerField(),
        ),
    ]
