# Generated by Django 5.0.7 on 2024-07-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_valeurinactive_nombre_valeur_feuillet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeurinactive',
            old_name='nombre_feuillets',
            new_name='nombre_de_feuillets',
        ),
        migrations.RenameField(
            model_name='valeurinactive',
            old_name='nombre_valeur_feuillet',
            new_name='nombre_de_valeur_feuillet_ou_carnet',
        ),
    ]
