# Generated by Django 5.0.7 on 2024-08-01 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0006_rename_nombre_feuillets_valeurinactive_nombre_de_feuillets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='date_mouvement',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='valeurinactive',
            name='date_enreg',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
