# Generated by Django 5.0.7 on 2024-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
