# Generated by Django 5.0.7 on 2024-07-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Commune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=8)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Commune.commune')),
            ],
        ),
    ]
