# Generated by Django 5.0.7 on 2024-08-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regisseur', '0001_initial'),
        ('Stock', '0007_alter_mouvementstock_date_mouvement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantite', models.PositiveIntegerField(default=1)),
                ('type_valeur', models.ManyToManyField(to='Stock.typevaleurinactive')),
                ('valeur_inactive', models.ManyToManyField(to='Stock.valeurinactive')),
            ],
        ),
    ]
