# Generated by Django 5.0.7 on 2024-08-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regisseur', '0004_remove_demande_date_demande_demande_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demande',
        ),
    ]
