# Generated by Django 5.0.7 on 2024-08-01 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regisseur', '0005_delete_demande'),
        ('Stock', '0007_alter_mouvementstock_date_mouvement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('regisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Regisseur.regisseur')),
                ('valeur_inactive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.valeurinactive')),
            ],
        ),
    ]
